language: php
	
sudo: false

cache:
  directories:
    - application/cache/

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 5.6
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true